version: '3'
services:
  client:
    image: 'gmuriel79/elem-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'gmuriel79/elem-server'
    mem_limit: 128m
    hostname: api
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  nginx:
    image: 'gmuriel79/elem-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
