# Generated by Django 5.0.6 on 2024-06-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
